### ISSUE TITLE
How to change server from tomcat 7 to tomcat 8

### ISSUE THREAD

**Issue by sonu0402** [in28minutes/SpringMvcStepByStep#12]
Hii, I want to know how the server could be changed to tomcat 8? Please tell me the plugin type for this issue.

**Comment by in28minutes** [comment]
Do you want to try this?

    <groupId>org.apache.tomcat.maven</groupId>
    <artifactId>tomcat8-maven-plugin</artifactId>
    <version>3.0-r1655215</version>

**Comment by sonu0402** [comment]
Sir, I am getting this error.[ERROR] No plugin found for prefix 'tomcat8' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Sonu\.m2\repository), central (http://repo.maven.apache.org/maven2)] -> [Help 1]

**Comment by sonu0402** [comment]
[ERROR] No plugin found for prefix 'tomcat8' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories

**Comment by in28minutes** [comment]
Did you get a chance to check this out -
https://stackoverflow.com/questions/24271213/tomcat-8-integration-with-maven

**Comment by sonu0402** [comment]
thanks sir
