### ISSUE TITLE
Having trouble at validation

### ISSUE THREAD

**Issue by sonu0402** [in28minutes/SpringMvcStepByStep#14]
Hello sir,
I am having trouble at step 27 while validating an **add-a-new-todo** request. When i enter more than 6 characters, the code executes normally. Although when i enter less than 6 chars, it returns; 

>  **java.lang.IllegalStateException: Neither BindingResult nor plain target object for bean name 'todo' available as request attribute.**

Rest of the code flows normally. Here is the code of add controller.

@RequestMapping(value = "/add-todos", method = RequestMethod.GET)
	public String showAddTodoPage(ModelMap model) {
		model.addAttribute("todo", new ToDoBean());
		return "add-todo";
	}
	@RequestMapping(value = "/add-todos", method = RequestMethod.POST)
	public String addTodo(ModelMap model, @Valid ToDoBean todoBean,
			BindingResult result) {

		if (result.hasErrors()) {
			return "add-todo";
		}
		String user = (String) model.get("name");
		todoService.addTodo(user, todoBean.getDesc(), new Date(), false);
		model.clear();// to prevent request parameter "name" to be passed
		return "redirect:/list-todos";
	}

I have uploaded the code here. Thank you sir.

[in28Minutes-first-webapp.zip](https://github.com/in28minutes/SpringMvcStepByStep/files/1130827/in28Minutes-first-webapp.zip)

**Comment by sonu0402** [comment]
I resolved the error by my self. Thanks

**Comment by ankitkeer** [comment]
Sir, I am also getting same error

**Comment by jstrainer** [comment]
> Hello sir,
> I am having trouble at step 27 while validating an **add-a-new-todo** request. When i enter more than 6 characters, the code executes normally. Although when i enter less than 6 chars, it returns;
> 
> > **java.lang.IllegalStateException: Neither BindingResult nor plain target object for bean name 'todo' available as request attribute.**
> 
> Rest of the code flows normally. Here is the code of add controller.
> 
> @RequestMapping(value = "/add-todos", method = RequestMethod.GET)
> public String showAddTodoPage(ModelMap model) {
> model.addAttribute("todo", new ToDoBean());
> return "add-todo";
> }
> @RequestMapping(value = "/add-todos", method = RequestMethod.POST)
> public String addTodo(ModelMap model, @Valid ToDoBean todoBean,
> BindingResult result) {
> 
> ```
> 	if (result.hasErrors()) {
> 		return "add-todo";
> 	}
> 	String user = (String) model.get("name");
> 	todoService.addTodo(user, todoBean.getDesc(), new Date(), false);
> 	model.clear();// to prevent request parameter "name" to be passed
> 	return "redirect:/list-todos";
> }
> ```
> I have uploaded the code here. Thank you sir.
> 
> [in28Minutes-first-webapp.zip](https://github.com/in28minutes/SpringMvcStepByStep/files/1130827/in28Minutes-first-webapp.zip)

Update method signature to:

`public String addTodo(@Valid @ModelAttribute("todoBean") ToDoBean todoBean, BindingResult result) {
//code goes here.
}`

**Comment by in28minutes** [comment]
Awesome. Do you want to submit a pull request?

**Comment by sonhandsome06** [comment]
okay you

Vào CN, 27 thg 1, 2019 vào lúc 13:22 in28minutes <notifications@github.com>
đã viết:

**Comment by sonhandsome06** [comment]
i'm not sure can help you but i will try to do it
:D

Vào CN, 27 thg 1, 2019 vào lúc 20:17 Optimus No <sonhandsome06@gmail.com>
đã viết:
