### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.web.SpringServletContainerInitializer

### ISSUE THREAD

**Issue by nenadbulatovic** [in28minutes/SpringMvcStepByStep#8]
This error happens because of:

https://github.com/in28minutes/SpringMvcStepByStep/blob/master/Step11.md

/pom.xml

<version>4.2.2.RELEASE</version>
just change it to

<version>4.2.3.RELEASE</version>
and it will work, no matter if you use Java 7 or Java 8

If you download project from GitHub, you can see that in Step11.zip there is version 4.2.3 while in Step07.zip there is version: 4.2.2

It would be great if this would be corrected in: https://github.com/in28minutes/SpringMvcStepByStep/blob/master/Step11.md

It took me some time to find cause of this error, might save time for some one else.

**Comment by in28minutes** [comment]
Thanks.. I've made the fix. Its great to have students like you.

**Comment by nenadbulatovic** [comment]
Thanks, You've fixed it in snippet but in ##Useful Snippets pom.xml but it is still 4.2.2 in Files List /pom.xml
